const mongoose = require('mongoose');

const userSchema = new mongoose.Schema({
    name: { type: String, required: true },
    email: { type: String, required: true, unique: true },
    password: { type: String, required: true },
    phone: String,
    whatsappNumber: String,
    chapter: { type: String, required: true },
    memberType: {
        type: String,
        enum: [
            // EO Dubai
            "EO Dubai Member", "EO Dubai Spouse", "EO Dubai Accelerator", "EO Dubai Next Gen", "EO Dubai Key Executive",
            // Other EO Chapters - Members
            "EO Adelaide Member", "EO Albany Member", "EO Andhra Pradesh Member", "EO APAC Bridge Member", "EO APAC Platinum One Bridge Member",
            "EO Argentina Member", "EO Arizona Member", "EO Atlanta Member", "EO Atlantic Canada Member", "EO Austin Member",
            "EO Austria Member", "EO Bahrain Member", "EO Baltimore Member", "EO Bangalore Member", "EO Bangkok Metropolitan Member",
            "EO Bangladesh Member", "EO Barcelona Member", "EO Beijing Member", "EO Beijing Metropolitan Member", "EO Belgium Member",
            "EO Berlin Member", "EO Beyond Japan Bridge Member", "EO Bhopal Member", "EO Birmingham Member", "EO Bogota Member",
            "EO Boston Member", "EO Cairo Member", "EO Calgary Member", "EO Canada Bridge Member", "EO Cancun-Riviera Maya Member",
            "EO Cape Town Member", "EO Charleston Member", "EO Charlotte Member", "EO Chengdu Member", "EO Chennai Member",
            "EO Chicago Member", "EO China East Member", "EO Cincinnati Member", "EO Cleveland Member", "EO Coimbatore Member",
            "EO Colorado Member", "EO Columbus Member", "EO Connecticut Member", "EO Costa Rica Member", "EO Dalian Member",
            "EO Dallas Member", "EO DC Member", "EO Detroit Member", "EO Dominican Republic Member", "EO Durban Member",
            "EO Edmonton Member", "EO El Salvador Member", "EO Europe Bridge Member", "EO Fort Worth Member", "EO Germany - Rhine Ruhr Member",
            "EO Germany - Southwest Member", "EO Goa Member", "EO Greater Bay Area Member", "EO Greater China Bridge Member",
            "EO Greece Member", "EO Guadalajara Member", "EO Guangzhou Member", "EO Guatemala Member", "EO Guayaquil Member",
            "EO Gujarat Member", "EO Gurgaon Member", "EO Hamburg Member", "EO Hawaii Member", "EO Hokkaido Member",
            "EO Hokuriku Member", "EO Hong Kong Member", "EO Houston Member", "EO Hyderabad Member", "EO Ibaraki Member",
            "EO Idaho Member", "EO Indianapolis Member", "EO Indonesia Member", "EO Indonesia East Member", "EO Indore Member",
            "EO Inland Empire Member", "EO Iowa Member", "EO Ireland Member", "EO Islamabad Member", "EO Israel Member",
            "EO Italy Member", "EO Jaipur Member", "EO Jammu and Kashmir Member", "EO Japan Korea Bridge Member", "EO Jeddah Member",
            "EO Johannesburg Member", "EO Jordan Member", "EO Kanagawa Member", "EO Kansai Metropolitan Member", "EO Kansas City Member",
            "EO Karachi Member", "EO Kelowna Member", "EO Kenya Member", "EO Kerala Member", "EO Kobe Member",
            "EO Kolkata Member", "EO Korea Member", "EO Kuwait Member", "EO Kyoto Member", "EO Kyushu Member",
            "EO LAC Bridge Member", "EO Lahore Member", "EO Las Vegas Member", "EO Lebanon Member", "EO Los Angeles Member",
            "EO Los Angeles - Valley Member", "EO Louisiana Member", "EO Madrid Member", "EO Malaysia Member", "EO Melbourne Member",
            "EO MEPA Bridge Member", "EO Merida Member", "EO Mexico City Member", "EO Minnesota Member", "EO Monterrey Member",
            "EO Montreal Member", "EO Morocco Member", "EO Mumbai Member", "EO Munich Member", "EO Nagoya Member",
            "EO Nagpur Member", "EO Nashville Member", "EO Navi Mumbai Member", "EO Nebraska Member", "EO Nepal Member",
            "EO Netherlands Member", "EO New Delhi Member", "EO Uganda Member",
            // Spouses for all chapters
            "EO Adelaide Spouse", "EO Albany Spouse", "EO Andhra Pradesh Spouse", "EO APAC Bridge Spouse", "EO APAC Platinum One Bridge Spouse",
            "EO Argentina Spouse", "EO Arizona Spouse", "EO Atlanta Spouse", "EO Atlantic Canada Spouse", "EO Austin Spouse",
            "EO Austria Spouse", "EO Bahrain Spouse", "EO Baltimore Spouse", "EO Bangalore Spouse", "EO Bangkok Metropolitan Spouse",
            "EO Bangladesh Spouse", "EO Barcelona Spouse", "EO Beijing Spouse", "EO Beijing Metropolitan Spouse", "EO Belgium Spouse",
            "EO Berlin Spouse", "EO Beyond Japan Bridge Spouse", "EO Bhopal Spouse", "EO Birmingham Spouse", "EO Bogota Spouse",
            "EO Boston Spouse", "EO Cairo Spouse", "EO Calgary Spouse", "EO Canada Bridge Spouse", "EO Cancun-Riviera Maya Spouse",
            "EO Cape Town Spouse", "EO Charleston Spouse", "EO Charlotte Spouse", "EO Chengdu Spouse", "EO Chennai Spouse",
            "EO Chicago Spouse", "EO China East Spouse", "EO Cincinnati Spouse", "EO Cleveland Spouse", "EO Coimbatore Spouse",
            "EO Colorado Spouse", "EO Columbus Spouse", "EO Connecticut Spouse", "EO Costa Rica Spouse", "EO Dalian Spouse",
            "EO Dallas Spouse", "EO DC Spouse", "EO Detroit Spouse", "EO Dominican Republic Spouse", "EO Durban Spouse",
            "EO Edmonton Spouse", "EO El Salvador Spouse", "EO Europe Bridge Spouse", "EO Fort Worth Spouse", "EO Germany - Rhine Ruhr Spouse",
            "EO Germany - Southwest Spouse", "EO Goa Spouse", "EO Greater Bay Area Spouse", "EO Greater China Bridge Spouse",
            "EO Greece Spouse", "EO Guadalajara Spouse", "EO Guangzhou Spouse", "EO Guatemala Spouse", "EO Guayaquil Spouse",
            "EO Gujarat Spouse", "EO Gurgaon Spouse", "EO Hamburg Spouse", "EO Hawaii Spouse", "EO Hokkaido Spouse",
            "EO Hokuriku Spouse", "EO Hong Kong Spouse", "EO Houston Spouse", "EO Hyderabad Spouse", "EO Ibaraki Spouse",
            "EO Idaho Spouse", "EO Indianapolis Spouse", "EO Indonesia Spouse", "EO Indonesia East Spouse", "EO Indore Spouse",
            "EO Inland Empire Spouse", "EO Iowa Spouse", "EO Ireland Spouse", "EO Islamabad Spouse", "EO Israel Spouse",
            "EO Italy Spouse", "EO Jaipur Spouse", "EO Jammu and Kashmir Spouse", "EO Japan Korea Bridge Spouse", "EO Jeddah Spouse",
            "EO Johannesburg Spouse", "EO Jordan Spouse", "EO Kanagawa Spouse", "EO Kansai Metropolitan Spouse", "EO Kansas City Spouse",
            "EO Karachi Spouse", "EO Kelowna Spouse", "EO Kenya Spouse", "EO Kerala Spouse", "EO Kobe Spouse",
            "EO Kolkata Spouse", "EO Korea Spouse", "EO Kuwait Spouse", "EO Kyoto Spouse", "EO Kyushu Spouse",
            "EO LAC Bridge Spouse", "EO Lahore Spouse", "EO Las Vegas Spouse", "EO Lebanon Spouse", "EO Los Angeles Spouse",
            "EO Los Angeles - Valley Spouse", "EO Louisiana Spouse", "EO Madrid Spouse", "EO Malaysia Spouse", "EO Melbourne Spouse",
            "EO MEPA Bridge Spouse", "EO Merida Spouse", "EO Mexico City Spouse", "EO Minnesota Spouse", "EO Monterrey Spouse",
            "EO Montreal Spouse", "EO Morocco Spouse", "EO Mumbai Spouse", "EO Munich Spouse", "EO Nagoya Spouse",
            "EO Nagpur Spouse", "EO Nashville Spouse", "EO Navi Mumbai Spouse", "EO Nebraska Spouse", "EO Nepal Spouse",
            "EO Netherlands Spouse", "EO New Delhi Spouse", "EO Uganda Spouse",
            // Accelerators for all chapters
            "EO Adelaide Accelerator", "EO Albany Accelerator", "EO Andhra Pradesh Accelerator", "EO APAC Bridge Accelerator", "EO APAC Platinum One Bridge Accelerator",
            "EO Argentina Accelerator", "EO Arizona Accelerator", "EO Atlanta Accelerator", "EO Atlantic Canada Accelerator", "EO Austin Accelerator",
            "EO Austria Accelerator", "EO Bahrain Accelerator", "EO Baltimore Accelerator", "EO Bangalore Accelerator", "EO Bangkok Metropolitan Accelerator",
            "EO Bangladesh Accelerator", "EO Barcelona Accelerator", "EO Beijing Accelerator", "EO Beijing Metropolitan Accelerator", "EO Belgium Accelerator",
            "EO Berlin Accelerator", "EO Beyond Japan Bridge Accelerator", "EO Bhopal Accelerator", "EO Birmingham Accelerator", "EO Bogota Accelerator",
            "EO Boston Accelerator", "EO Cairo Accelerator", "EO Calgary Accelerator", "EO Canada Bridge Accelerator", "EO Cancun-Riviera Maya Accelerator",
            "EO Cape Town Accelerator", "EO Charleston Accelerator", "EO Charlotte Accelerator", "EO Chengdu Accelerator", "EO Chennai Accelerator",
            "EO Chicago Accelerator", "EO China East Accelerator", "EO Cincinnati Accelerator", "EO Cleveland Accelerator", "EO Coimbatore Accelerator",
            "EO Colorado Accelerator", "EO Columbus Accelerator", "EO Connecticut Accelerator", "EO Costa Rica Accelerator", "EO Dalian Accelerator",
            "EO Dallas Accelerator", "EO DC Accelerator", "EO Detroit Accelerator", "EO Dominican Republic Accelerator", "EO Durban Accelerator",
            "EO Edmonton Accelerator", "EO El Salvador Accelerator", "EO Europe Bridge Accelerator", "EO Fort Worth Accelerator", "EO Germany - Rhine Ruhr Accelerator",
            "EO Germany - Southwest Accelerator", "EO Goa Accelerator", "EO Greater Bay Area Accelerator", "EO Greater China Bridge Accelerator",
            "EO Greece Accelerator", "EO Guadalajara Accelerator", "EO Guangzhou Accelerator", "EO Guatemala Accelerator", "EO Guayaquil Accelerator",
            "EO Gujarat Accelerator", "EO Gurgaon Accelerator", "EO Hamburg Accelerator", "EO Hawaii Accelerator", "EO Hokkaido Accelerator",
            "EO Hokuriku Accelerator", "EO Hong Kong Accelerator", "EO Houston Accelerator", "EO Hyderabad Accelerator", "EO Ibaraki Accelerator",
            "EO Idaho Accelerator", "EO Indianapolis Accelerator", "EO Indonesia Accelerator", "EO Indonesia East Accelerator", "EO Indore Accelerator",
            "EO Inland Empire Accelerator", "EO Iowa Accelerator", "EO Ireland Accelerator", "EO Islamabad Accelerator", "EO Israel Accelerator",
            "EO Italy Accelerator", "EO Jaipur Accelerator", "EO Jammu and Kashmir Accelerator", "EO Japan Korea Bridge Accelerator", "EO Jeddah Accelerator",
            "EO Johannesburg Accelerator", "EO Jordan Accelerator", "EO Kanagawa Accelerator", "EO Kansai Metropolitan Accelerator", "EO Kansas City Accelerator",
            "EO Karachi Accelerator", "EO Kelowna Accelerator", "EO Kenya Accelerator", "EO Kerala Accelerator", "EO Kobe Accelerator",
            "EO Kolkata Accelerator", "EO Korea Accelerator", "EO Kuwait Accelerator", "EO Kyoto Accelerator", "EO Kyushu Accelerator",
            "EO LAC Bridge Accelerator", "EO Lahore Accelerator", "EO Las Vegas Accelerator", "EO Lebanon Accelerator", "EO Los Angeles Accelerator",
            "EO Los Angeles - Valley Accelerator", "EO Louisiana Accelerator", "EO Madrid Accelerator", "EO Malaysia Accelerator", "EO Melbourne Accelerator",
            "EO MEPA Bridge Accelerator", "EO Merida Accelerator", "EO Mexico City Accelerator", "EO Minnesota Accelerator", "EO Monterrey Accelerator",
            "EO Montreal Accelerator", "EO Morocco Accelerator", "EO Mumbai Accelerator", "EO Munich Accelerator", "EO Nagoya Accelerator",
            "EO Nagpur Accelerator", "EO Nashville Accelerator", "EO Navi Mumbai Accelerator", "EO Nebraska Accelerator", "EO Nepal Accelerator",
            "EO Netherlands Accelerator", "EO New Delhi Accelerator", "EO Uganda Accelerator",
            // Key Executives for all chapters
            "EO Adelaide Key Executive", "EO Albany Key Executive", "EO Andhra Pradesh Key Executive", "EO APAC Bridge Key Executive", "EO APAC Platinum One Bridge Key Executive",
            "EO Argentina Key Executive", "EO Arizona Key Executive", "EO Atlanta Key Executive", "EO Atlantic Canada Key Executive", "EO Austin Key Executive",
            "EO Austria Key Executive", "EO Bahrain Key Executive", "EO Baltimore Key Executive", "EO Bangalore Key Executive", "EO Bangkok Metropolitan Key Executive",
            "EO Bangladesh Key Executive", "EO Barcelona Key Executive", "EO Beijing Key Executive", "EO Beijing Metropolitan Key Executive", "EO Belgium Key Executive",
            "EO Berlin Key Executive", "EO Beyond Japan Bridge Key Executive", "EO Bhopal Key Executive", "EO Birmingham Key Executive", "EO Bogota Key Executive",
            "EO Boston Key Executive", "EO Cairo Key Executive", "EO Calgary Key Executive", "EO Canada Bridge Key Executive", "EO Cancun-Riviera Maya Key Executive",
            "EO Cape Town Key Executive", "EO Charleston Key Executive", "EO Charlotte Key Executive", "EO Chengdu Key Executive", "EO Chennai Key Executive",
            "EO Chicago Key Executive", "EO China East Key Executive", "EO Cincinnati Key Executive", "EO Cleveland Key Executive", "EO Coimbatore Key Executive",
            "EO Colorado Key Executive", "EO Columbus Key Executive", "EO Connecticut Key Executive", "EO Costa Rica Key Executive", "EO Dalian Key Executive",
            "EO Dallas Key Executive", "EO DC Key Executive", "EO Detroit Key Executive", "EO Dominican Republic Key Executive", "EO Durban Key Executive",
            "EO Edmonton Key Executive", "EO El Salvador Key Executive", "EO Europe Bridge Key Executive", "EO Fort Worth Key Executive", "EO Germany - Rhine Ruhr Key Executive",
            "EO Germany - Southwest Key Executive", "EO Goa Key Executive", "EO Greater Bay Area Key Executive", "EO Greater China Bridge Key Executive",
            "EO Greece Key Executive", "EO Guadalajara Key Executive", "EO Guangzhou Key Executive", "EO Guatemala Key Executive", "EO Guayaquil Key Executive",
            "EO Gujarat Key Executive", "EO Gurgaon Key Executive", "EO Hamburg Key Executive", "EO Hawaii Key Executive", "EO Hokkaido Key Executive",
            "EO Hokuriku Key Executive", "EO Hong Kong Key Executive", "EO Houston Key Executive", "EO Hyderabad Key Executive", "EO Ibaraki Key Executive",
            "EO Idaho Key Executive", "EO Indianapolis Key Executive", "EO Indonesia Key Executive", "EO Indonesia East Key Executive", "EO Indore Key Executive",
            "EO Inland Empire Key Executive", "EO Iowa Key Executive", "EO Ireland Key Executive", "EO Islamabad Key Executive", "EO Israel Key Executive",
            "EO Italy Key Executive", "EO Jaipur Key Executive", "EO Jammu and Kashmir Key Executive", "EO Japan Korea Bridge Key Executive", "EO Jeddah Key Executive",
            "EO Johannesburg Key Executive", "EO Jordan Key Executive", "EO Kanagawa Key Executive", "EO Kansai Metropolitan Key Executive", "EO Kansas City Key Executive",
            "EO Karachi Key Executive", "EO Kelowna Key Executive", "EO Kenya Key Executive", "EO Kerala Key Executive", "EO Kobe Key Executive",
            "EO Kolkata Key Executive", "EO Korea Key Executive", "EO Kuwait Key Executive", "EO Kyoto Key Executive", "EO Kyushu Key Executive",
            "EO LAC Bridge Key Executive", "EO Lahore Key Executive", "EO Las Vegas Key Executive", "EO Lebanon Key Executive", "EO Los Angeles Key Executive",
            "EO Los Angeles - Valley Key Executive", "EO Louisiana Key Executive", "EO Madrid Key Executive", "EO Malaysia Key Executive", "EO Melbourne Key Executive",
            "EO MEPA Bridge Key Executive", "EO Merida Key Executive", "EO Mexico City Key Executive", "EO Minnesota Key Executive", "EO Monterrey Key Executive",
            "EO Montreal Key Executive", "EO Morocco Key Executive", "EO Mumbai Key Executive", "EO Munich Key Executive", "EO Nagoya Key Executive",
            "EO Nagpur Key Executive", "EO Nashville Key Executive", "EO Navi Mumbai Key Executive", "EO Nebraska Key Executive", "EO Nepal Key Executive",
            "EO Netherlands Key Executive", "EO New Delhi Key Executive", "EO Uganda Key Executive",
            // Next Gen for all chapters
            "EO Adelaide Next Gen", "EO Albany Next Gen", "EO Andhra Pradesh Next Gen", "EO APAC Bridge Next Gen", "EO APAC Platinum One Bridge Next Gen",
            "EO Argentina Next Gen", "EO Arizona Next Gen", "EO Atlanta Next Gen", "EO Atlantic Canada Next Gen", "EO Austin Next Gen",
            "EO Austria Next Gen", "EO Bahrain Next Gen", "EO Baltimore Next Gen", "EO Bangalore Next Gen", "EO Bangkok Metropolitan Next Gen",
            "EO Bangladesh Next Gen", "EO Barcelona Next Gen", "EO Beijing Next Gen", "EO Beijing Metropolitan Next Gen", "EO Belgium Next Gen",
            "EO Berlin Next Gen", "EO Beyond Japan Bridge Next Gen", "EO Bhopal Next Gen", "EO Birmingham Next Gen", "EO Bogota Next Gen",
            "EO Boston Next Gen", "EO Cairo Next Gen", "EO Calgary Next Gen", "EO Canada Bridge Next Gen", "EO Cancun-Riviera Maya Next Gen",
            "EO Cape Town Next Gen", "EO Charleston Next Gen", "EO Charlotte Next Gen", "EO Chengdu Next Gen", "EO Chennai Next Gen",
            "EO Chicago Next Gen", "EO China East Next Gen", "EO Cincinnati Next Gen", "EO Cleveland Next Gen", "EO Coimbatore Next Gen",
            "EO Colorado Next Gen", "EO Columbus Next Gen", "EO Connecticut Next Gen", "EO Costa Rica Next Gen", "EO Dalian Next Gen",
            "EO Dallas Next Gen", "EO DC Next Gen", "EO Detroit Next Gen", "EO Dominican Republic Next Gen", "EO Durban Next Gen",
            "EO Edmonton Next Gen", "EO El Salvador Next Gen", "EO Europe Bridge Next Gen", "EO Fort Worth Next Gen", "EO Germany - Rhine Ruhr Next Gen",
            "EO Germany - Southwest Next Gen", "EO Goa Next Gen", "EO Greater Bay Area Next Gen", "EO Greater China Bridge Next Gen",
            "EO Greece Next Gen", "EO Guadalajara Next Gen", "EO Guangzhou Next Gen", "EO Guatemala Next Gen", "EO Guayaquil Next Gen",
            "EO Gujarat Next Gen", "EO Gurgaon Next Gen", "EO Hamburg Next Gen", "EO Hawaii Next Gen", "EO Hokkaido Next Gen",
            "EO Hokuriku Next Gen", "EO Hong Kong Next Gen", "EO Houston Next Gen", "EO Hyderabad Next Gen", "EO Ibaraki Next Gen",
            "EO Idaho Next Gen", "EO Indianapolis Next Gen", "EO Indonesia Next Gen", "EO Indonesia East Next Gen", "EO Indore Next Gen",
            "EO Inland Empire Next Gen", "EO Iowa Next Gen", "EO Ireland Next Gen", "EO Islamabad Next Gen", "EO Israel Next Gen",
            "EO Italy Next Gen", "EO Jaipur Next Gen", "EO Jammu and Kashmir Next Gen", "EO Japan Korea Bridge Next Gen", "EO Jeddah Next Gen",
            "EO Johannesburg Next Gen", "EO Jordan Next Gen", "EO Kanagawa Next Gen", "EO Kansai Metropolitan Next Gen", "EO Kansas City Next Gen",
            "EO Karachi Next Gen", "EO Kelowna Next Gen", "EO Kenya Next Gen", "EO Kerala Next Gen", "EO Kobe Next Gen",
            "EO Kolkata Next Gen", "EO Korea Next Gen", "EO Kuwait Next Gen", "EO Kyoto Next Gen", "EO Kyushu Next Gen",
            "EO LAC Bridge Next Gen", "EO Lahore Next Gen", "EO Las Vegas Next Gen", "EO Lebanon Next Gen", "EO Los Angeles Next Gen",
            "EO Los Angeles - Valley Next Gen", "EO Louisiana Next Gen", "EO Madrid Next Gen", "EO Malaysia Next Gen", "EO Melbourne Next Gen",
            "EO MEPA Bridge Next Gen", "EO Merida Next Gen", "EO Mexico City Next Gen", "EO Minnesota Next Gen", "EO Monterrey Next Gen",
            "EO Montreal Next Gen", "EO Morocco Next Gen", "EO Mumbai Next Gen", "EO Munich Next Gen", "EO Nagoya Next Gen",
            "EO Nagpur Next Gen", "EO Nashville Next Gen", "EO Navi Mumbai Next Gen", "EO Nebraska Next Gen", "EO Nepal Next Gen",
            "EO Netherlands Next Gen", "EO New Delhi Next Gen", "EO Uganda Next Gen",
            // Guest option
            "Guest"
        ],
        required: true
    },
    role: {
        type: String,
        enum: ["admin", "organizer", "member", "guest"],
        default: "member"
    },
    permissions: [{
        type: String,
        enum: ["create_events", "edit_events", "delete_events", "manage_registrations", "view_reports", "manage_users", "send_notifications"]
    }],
    profileImage: String,
    isActive: { type: Boolean, default: true },
    emailVerified: { type: Boolean, default: false },
    telrCardToken: String,
    preferences: {
        emailNotifications: { type: Boolean, default: true },
        whatsappNotifications: { type: Boolean, default: true },
        eventReminders: { type: Boolean, default: true }
    }
}, { timestamps: true });

module.exports = mongoose.model("User", userSchema);
